# Setup
title:            'Presence Health Community Benefit'
url:              http://presencehealth.github.io/communitybenefit
author:
  name:           'Jonathan Giuffrida'

# Custom vars
version:          0.1

github:
  repo:           http://github.com/presencehealth/communitybenefit
